import type {
  Member,
  Fact,
  ExternalSignal,
  OpportunityItem,
  MessageDraft,
  InteractionLog,
  OutcomeFeedback,
  IntroSuggestion,
  IntroRecord,
  Perk,
  PerkRecommendation,
  PerkPartnerApplication,
  MastermindGroup,
  MonthlyClubAgenda,
  WorkshopPlan,
  KnowledgeResource,
  Survey,
  Pod,
  ForcedSuccessItem,
  AuditLogEntry,
  ChatThread,
  PersonaCluster,
  NotificationItem,
  TenantId,
  MemberWrapped, // Added for mockWrapped
} from "./types"

// ============================================================================
// HELPERS
// ============================================================================

const generateId = () => Math.random().toString(36).substring(2, 11)
const randomDate = (daysAgo: number) => {
  const date = new Date()
  date.setDate(date.getDate() - Math.floor(Math.random() * daysAgo))
  return date.toISOString()
}
const futureDate = (daysAhead: number) => {
  const date = new Date()
  date.setDate(date.getDate() + Math.floor(Math.random() * daysAhead) + 1)
  return date.toISOString()
}

// ============================================================================
// MEMBERS (25 realistic members)
// ============================================================================

export const mockMembers: Member[] = [
  {
    id: "mem_001",
    tenantId: "b2b",
    firstName: "Sarah",
    lastName: "Chen",
    email: "sarah@techscale.io",
    avatarUrl: "/professional-asian-woman.png",
    linkedInUrl: "https://linkedin.com/in/sarahchen",
    company: {
      name: "TechScale",
      role: "VP Marketing",
      website: "techscale.io",
      stage: "Series B",
      headcount: "150-200",
      industry: "B2B SaaS",
    },
    status: "active",
    joinedAt: "2024-03-15T00:00:00Z",
    renewalDate: "2026-03-15T00:00:00Z",
    riskTier: "green",
    riskScore: 15,
    engagementScore: 85,
    lastEngagementAt: "2025-12-28T00:00:00Z",
    contactState: "open",
    lastContactedAt: "2025-12-20T00:00:00Z",
    lastValueDropAt: "2025-12-20T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-03-18T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2024-03-20T00:00:00Z",
      introPackDelivered: true,
      profileVerified: true,
    },
    tags: ["enterprise", "product-led", "high-growth"],
    createdAt: "2024-03-15T00:00:00Z",
    updatedAt: "2025-12-28T00:00:00Z",
  },
  {
    id: "mem_002",
    tenantId: "b2b",
    firstName: "Marcus",
    lastName: "Johnson",
    email: "marcus@growthengine.co",
    avatarUrl: "/professional-black-man.png",
    linkedInUrl: "https://linkedin.com/in/marcusjohnson",
    company: {
      name: "GrowthEngine",
      role: "CMO",
      website: "growthengine.co",
      stage: "Series A",
      headcount: "50-75",
      industry: "MarTech",
    },
    status: "active",
    joinedAt: "2024-06-01T00:00:00Z",
    renewalDate: "2026-02-01T00:00:00Z",
    riskTier: "yellow",
    riskScore: 45,
    engagementScore: 55,
    lastEngagementAt: "2025-12-10T00:00:00Z",
    contactState: "open",
    lastContactedAt: "2025-11-28T00:00:00Z",
    lastValueDropAt: "2025-11-15T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-06-05T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2024-06-10T00:00:00Z",
      introPackDelivered: true,
      profileVerified: false,
    },
    tags: ["plg", "content-marketing", "scaling"],
    createdAt: "2024-06-01T00:00:00Z",
    updatedAt: "2025-12-10T00:00:00Z",
  },
  {
    id: "mem_003",
    tenantId: "b2b",
    firstName: "Elena",
    lastName: "Rodriguez",
    email: "elena@dataflow.ai",
    avatarUrl: "/latina-professional-woman.png",
    linkedInUrl: "https://linkedin.com/in/elenarodriguez",
    company: {
      name: "DataFlow AI",
      role: "Head of Marketing",
      website: "dataflow.ai",
      stage: "Seed",
      headcount: "15-25",
      industry: "AI/ML",
    },
    status: "active",
    joinedAt: "2024-09-10T00:00:00Z",
    renewalDate: "2026-01-10T00:00:00Z",
    riskTier: "red",
    riskScore: 75,
    engagementScore: 25,
    lastEngagementAt: "2025-11-05T00:00:00Z",
    contactState: "open",
    lastContactedAt: "2025-12-01T00:00:00Z",
    lastValueDropAt: "2025-10-20T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-09-15T00:00:00Z",
      welcomeCallCompleted: false,
      introPackDelivered: false,
      profileVerified: false,
    },
    tags: ["early-stage", "ai-native", "technical-founder"],
    createdAt: "2024-09-10T00:00:00Z",
    updatedAt: "2025-12-01T00:00:00Z",
  },
  {
    id: "mem_004",
    tenantId: "b2b",
    firstName: "David",
    lastName: "Kim",
    email: "david@cloudnative.dev",
    avatarUrl: "/professional-korean-man.png",
    linkedInUrl: "https://linkedin.com/in/davidkim",
    company: {
      name: "CloudNative",
      role: "VP Growth",
      website: "cloudnative.dev",
      stage: "Series C",
      headcount: "300-500",
      industry: "DevTools",
    },
    status: "active",
    joinedAt: "2024-01-20T00:00:00Z",
    renewalDate: "2026-01-20T00:00:00Z",
    riskTier: "green",
    riskScore: 10,
    engagementScore: 92,
    lastEngagementAt: "2025-12-30T00:00:00Z",
    contactState: "open",
    lastContactedAt: "2025-12-25T00:00:00Z",
    lastValueDropAt: "2025-12-25T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-01-22T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2024-01-25T00:00:00Z",
      introPackDelivered: true,
      profileVerified: true,
    },
    tags: ["enterprise", "developer-marketing", "community"],
    createdAt: "2024-01-20T00:00:00Z",
    updatedAt: "2025-12-30T00:00:00Z",
  },
  {
    id: "mem_005",
    tenantId: "b2b",
    firstName: "Amanda",
    lastName: "Foster",
    email: "amanda@revops.io",
    avatarUrl: "/professional-blonde-woman.png",
    linkedInUrl: "https://linkedin.com/in/amandafoster",
    company: {
      name: "RevOps Pro",
      role: "CMO",
      website: "revops.io",
      stage: "Series A",
      headcount: "75-100",
      industry: "RevTech",
    },
    status: "active",
    joinedAt: "2024-07-15T00:00:00Z",
    renewalDate: "2026-01-15T00:00:00Z",
    riskTier: "yellow",
    riskScore: 40,
    engagementScore: 60,
    lastEngagementAt: "2025-12-15T00:00:00Z",
    contactState: "open",
    lastContactedAt: "2025-12-10T00:00:00Z",
    lastValueDropAt: "2025-12-05T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-07-18T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2024-07-22T00:00:00Z",
      introPackDelivered: true,
      profileVerified: true,
    },
    tags: ["abm", "sales-alignment", "data-driven"],
    createdAt: "2024-07-15T00:00:00Z",
    updatedAt: "2025-12-15T00:00:00Z",
  },
  {
    id: "mem_006",
    tenantId: "b2b",
    firstName: "James",
    lastName: "Wilson",
    email: "james@fintech.io",
    avatarUrl: "/professional-man-suit.png",
    linkedInUrl: "https://linkedin.com/in/jameswilson",
    company: {
      name: "FinTech Solutions",
      role: "Head of Marketing",
      website: "fintech.io",
      stage: "Series B",
      headcount: "100-150",
      industry: "FinTech",
    },
    status: "active",
    joinedAt: "2024-04-01T00:00:00Z",
    renewalDate: "2026-04-01T00:00:00Z",
    riskTier: "green",
    riskScore: 20,
    engagementScore: 78,
    lastEngagementAt: "2025-12-27T00:00:00Z",
    contactState: "open",
    lastContactedAt: "2025-12-22T00:00:00Z",
    lastValueDropAt: "2025-12-18T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-04-05T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2024-04-08T00:00:00Z",
      introPackDelivered: true,
      profileVerified: true,
    },
    tags: ["regulated", "enterprise-sales", "compliance"],
    createdAt: "2024-04-01T00:00:00Z",
    updatedAt: "2025-12-27T00:00:00Z",
  },
  {
    id: "mem_007",
    tenantId: "b2b",
    firstName: "Priya",
    lastName: "Patel",
    email: "priya@healthtech.co",
    avatarUrl: "/professional-indian-woman.png",
    linkedInUrl: "https://linkedin.com/in/priyapatel",
    company: {
      name: "HealthTech Co",
      role: "VP Marketing",
      website: "healthtech.co",
      stage: "Series A",
      headcount: "40-60",
      industry: "HealthTech",
    },
    status: "active",
    joinedAt: "2024-08-20T00:00:00Z",
    renewalDate: "2026-02-20T00:00:00Z",
    riskTier: "red",
    riskScore: 68,
    engagementScore: 30,
    lastEngagementAt: "2025-11-20T00:00:00Z",
    contactState: "closed",
    lastContactedAt: "2025-12-28T00:00:00Z",
    lastValueDropAt: "2025-11-10T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-08-25T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2024-08-28T00:00:00Z",
      introPackDelivered: true,
      profileVerified: false,
    },
    tags: ["hipaa", "b2b2c", "regulated"],
    createdAt: "2024-08-20T00:00:00Z",
    updatedAt: "2025-12-28T00:00:00Z",
  },
  {
    id: "mem_008",
    tenantId: "b2b",
    firstName: "Michael",
    lastName: "Brown",
    email: "michael@securityfirst.io",
    avatarUrl: "/professional-man-glasses.jpg",
    linkedInUrl: "https://linkedin.com/in/michaelbrown",
    company: {
      name: "SecurityFirst",
      role: "CMO",
      website: "securityfirst.io",
      stage: "Series B",
      headcount: "80-120",
      industry: "Cybersecurity",
    },
    status: "active",
    joinedAt: "2024-02-10T00:00:00Z",
    renewalDate: "2026-02-10T00:00:00Z",
    riskTier: "green",
    riskScore: 12,
    engagementScore: 88,
    lastEngagementAt: "2025-12-29T00:00:00Z",
    contactState: "open",
    lastContactedAt: "2025-12-26T00:00:00Z",
    lastValueDropAt: "2025-12-26T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-02-12T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2024-02-15T00:00:00Z",
      introPackDelivered: true,
      profileVerified: true,
    },
    tags: ["enterprise", "channel-marketing", "events"],
    createdAt: "2024-02-10T00:00:00Z",
    updatedAt: "2025-12-29T00:00:00Z",
  },
  {
    id: "mem_009",
    tenantId: "b2b",
    firstName: "Lisa",
    lastName: "Thompson",
    email: "lisa@hrplatform.com",
    avatarUrl: "/professional-woman-redhead.jpg",
    linkedInUrl: "https://linkedin.com/in/lisathompson",
    company: {
      name: "HR Platform",
      role: "Head of Growth",
      website: "hrplatform.com",
      stage: "Series A",
      headcount: "30-50",
      industry: "HRTech",
    },
    status: "active",
    joinedAt: "2024-10-05T00:00:00Z",
    renewalDate: "2026-04-05T00:00:00Z",
    riskTier: "yellow",
    riskScore: 50,
    engagementScore: 45,
    lastEngagementAt: "2025-12-08T00:00:00Z",
    contactState: "open",
    lastContactedAt: "2025-12-05T00:00:00Z",
    lastValueDropAt: "2025-11-25T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-10-10T00:00:00Z",
      welcomeCallCompleted: false,
      introPackDelivered: true,
      profileVerified: false,
    },
    tags: ["smb-focus", "content-led", "partnership"],
    createdAt: "2024-10-05T00:00:00Z",
    updatedAt: "2025-12-08T00:00:00Z",
  },
  {
    id: "mem_010",
    tenantId: "b2b",
    firstName: "Robert",
    lastName: "Garcia",
    email: "robert@logisticspro.io",
    avatarUrl: "/professional-hispanic-man.png",
    linkedInUrl: "https://linkedin.com/in/robertgarcia",
    company: {
      name: "LogisticsPro",
      role: "VP Marketing",
      website: "logisticspro.io",
      stage: "Series C",
      headcount: "200-300",
      industry: "Logistics",
    },
    status: "active",
    joinedAt: "2024-05-15T00:00:00Z",
    renewalDate: "2026-05-15T00:00:00Z",
    riskTier: "green",
    riskScore: 18,
    engagementScore: 82,
    lastEngagementAt: "2025-12-26T00:00:00Z",
    contactState: "open",
    lastContactedAt: "2025-12-20T00:00:00Z",
    lastValueDropAt: "2025-12-20T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-05-18T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2024-05-22T00:00:00Z",
      introPackDelivered: true,
      profileVerified: true,
    },
    tags: ["enterprise", "field-marketing", "global"],
    createdAt: "2024-05-15T00:00:00Z",
    updatedAt: "2025-12-26T00:00:00Z",
  },
  {
    id: "mem_011",
    tenantId: "b2b",
    firstName: "Jennifer",
    lastName: "Lee",
    email: "jennifer@edtech.io",
    avatarUrl: "/professional-woman-asian-glasses.jpg",
    linkedInUrl: "https://linkedin.com/in/jenniferlee",
    company: {
      name: "EdTech Innovations",
      role: "CMO",
      website: "edtech.io",
      stage: "Series A",
      headcount: "25-40",
      industry: "EdTech",
    },
    status: "active",
    joinedAt: "2024-11-01T00:00:00Z",
    renewalDate: "2026-05-01T00:00:00Z",
    riskTier: "yellow",
    riskScore: 35,
    engagementScore: 65,
    lastEngagementAt: "2025-12-18T00:00:00Z",
    contactState: "open",
    lastContactedAt: "2025-12-15T00:00:00Z",
    lastValueDropAt: "2025-12-10T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-11-05T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2024-11-08T00:00:00Z",
      introPackDelivered: true,
      profileVerified: true,
    },
    tags: ["b2b2c", "institutional-sales", "content"],
    createdAt: "2024-11-01T00:00:00Z",
    updatedAt: "2025-12-18T00:00:00Z",
  },
  {
    id: "mem_012",
    tenantId: "b2b",
    firstName: "Chris",
    lastName: "Anderson",
    email: "chris@proptech.co",
    avatarUrl: "/professional-man-beard.png",
    linkedInUrl: "https://linkedin.com/in/chrisanderson",
    company: {
      name: "PropTech Solutions",
      role: "Head of Marketing",
      website: "proptech.co",
      stage: "Seed",
      headcount: "10-20",
      industry: "PropTech",
    },
    status: "active",
    joinedAt: "2024-12-01T00:00:00Z",
    renewalDate: "2026-06-01T00:00:00Z",
    riskTier: "green",
    riskScore: 22,
    engagementScore: 70,
    lastEngagementAt: "2025-12-28T00:00:00Z",
    contactState: "open",
    lastContactedAt: "2025-12-25T00:00:00Z",
    lastValueDropAt: "2025-12-25T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-12-05T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2024-12-10T00:00:00Z",
      introPackDelivered: true,
      profileVerified: true,
    },
    tags: ["early-stage", "real-estate", "b2b"],
    createdAt: "2024-12-01T00:00:00Z",
    updatedAt: "2025-12-28T00:00:00Z",
  },
  {
    id: "mem_013",
    tenantId: "b2b",
    firstName: "Nicole",
    lastName: "Martinez",
    email: "nicole@legaltech.io",
    avatarUrl: "/professional-woman-brunette.jpg",
    linkedInUrl: "https://linkedin.com/in/nicolemartinez",
    company: {
      name: "LegalTech Pro",
      role: "VP Marketing",
      website: "legaltech.io",
      stage: "Series B",
      headcount: "60-90",
      industry: "LegalTech",
    },
    status: "active",
    joinedAt: "2024-03-01T00:00:00Z",
    renewalDate: "2026-03-01T00:00:00Z",
    riskTier: "green",
    riskScore: 15,
    engagementScore: 85,
    lastEngagementAt: "2025-12-29T00:00:00Z",
    contactState: "open",
    lastContactedAt: "2025-12-27T00:00:00Z",
    lastValueDropAt: "2025-12-27T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-03-05T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2024-03-08T00:00:00Z",
      introPackDelivered: true,
      profileVerified: true,
    },
    tags: ["regulated", "enterprise", "thought-leadership"],
    createdAt: "2024-03-01T00:00:00Z",
    updatedAt: "2025-12-29T00:00:00Z",
  },
  {
    id: "mem_014",
    tenantId: "b2b",
    firstName: "Tom",
    lastName: "Harris",
    email: "tom@retailtech.com",
    avatarUrl: "/professional-man-young.jpg",
    linkedInUrl: "https://linkedin.com/in/tomharris",
    company: {
      name: "RetailTech",
      role: "CMO",
      website: "retailtech.com",
      stage: "Series A",
      headcount: "35-55",
      industry: "Retail Tech",
    },
    status: "active",
    joinedAt: "2024-09-01T00:00:00Z",
    renewalDate: "2026-03-01T00:00:00Z",
    riskTier: "red",
    riskScore: 72,
    engagementScore: 28,
    lastEngagementAt: "2025-11-10T00:00:00Z",
    contactState: "open",
    lastContactedAt: "2025-12-15T00:00:00Z",
    lastValueDropAt: "2025-10-25T00:00:00Z",
    onboarding: {
      intakeCompleted: false,
      welcomeCallCompleted: false,
      introPackDelivered: false,
      profileVerified: false,
    },
    tags: ["retail", "omnichannel", "b2b2c"],
    createdAt: "2024-09-01T00:00:00Z",
    updatedAt: "2025-12-15T00:00:00Z",
  },
  {
    id: "mem_015",
    tenantId: "b2b",
    firstName: "Emily",
    lastName: "White",
    email: "emily@cleantech.io",
    avatarUrl: "/professional-woman-short-hair.jpg",
    linkedInUrl: "https://linkedin.com/in/emilywhite",
    company: {
      name: "CleanTech Solutions",
      role: "Head of Growth",
      website: "cleantech.io",
      stage: "Series B",
      headcount: "70-100",
      industry: "CleanTech",
    },
    status: "active",
    joinedAt: "2024-06-15T00:00:00Z",
    renewalDate: "2026-06-15T00:00:00Z",
    riskTier: "green",
    riskScore: 20,
    engagementScore: 75,
    lastEngagementAt: "2025-12-24T00:00:00Z",
    contactState: "open",
    lastContactedAt: "2025-12-20T00:00:00Z",
    lastValueDropAt: "2025-12-18T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-06-18T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2024-06-22T00:00:00Z",
      introPackDelivered: true,
      profileVerified: true,
    },
    tags: ["sustainability", "enterprise", "government"],
    createdAt: "2024-06-15T00:00:00Z",
    updatedAt: "2025-12-24T00:00:00Z",
  },
  {
    id: "mem_016",
    tenantId: "b2b",
    firstName: "Alex",
    lastName: "Taylor",
    email: "alex@agtech.co",
    avatarUrl: "/professional-person-neutral.jpg",
    linkedInUrl: "https://linkedin.com/in/alextaylor",
    company: {
      name: "AgTech Innovations",
      role: "VP Marketing",
      website: "agtech.co",
      stage: "Series A",
      headcount: "20-35",
      industry: "AgTech",
    },
    status: "active",
    joinedAt: "2024-10-15T00:00:00Z",
    renewalDate: "2026-04-15T00:00:00Z",
    riskTier: "yellow",
    riskScore: 42,
    engagementScore: 52,
    lastEngagementAt: "2025-12-12T00:00:00Z",
    contactState: "open",
    lastContactedAt: "2025-12-08T00:00:00Z",
    lastValueDropAt: "2025-12-01T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-10-20T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2024-10-25T00:00:00Z",
      introPackDelivered: true,
      profileVerified: false,
    },
    tags: ["agriculture", "iot", "sustainability"],
    createdAt: "2024-10-15T00:00:00Z",
    updatedAt: "2025-12-12T00:00:00Z",
  },
  {
    id: "mem_017",
    tenantId: "b2b",
    firstName: "Rachel",
    lastName: "Green",
    email: "rachel@traveltech.io",
    avatarUrl: "/professional-woman-curly-hair.jpg",
    linkedInUrl: "https://linkedin.com/in/rachelgreen",
    company: {
      name: "TravelTech",
      role: "CMO",
      website: "traveltech.io",
      stage: "Series B",
      headcount: "90-130",
      industry: "Travel Tech",
    },
    status: "active",
    joinedAt: "2024-04-20T00:00:00Z",
    renewalDate: "2026-04-20T00:00:00Z",
    riskTier: "green",
    riskScore: 18,
    engagementScore: 80,
    lastEngagementAt: "2025-12-27T00:00:00Z",
    contactState: "open",
    lastContactedAt: "2025-12-23T00:00:00Z",
    lastValueDropAt: "2025-12-23T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-04-25T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2024-04-28T00:00:00Z",
      introPackDelivered: true,
      profileVerified: true,
    },
    tags: ["b2b2c", "consumer", "global"],
    createdAt: "2024-04-20T00:00:00Z",
    updatedAt: "2025-12-27T00:00:00Z",
  },
  {
    id: "mem_018",
    tenantId: "b2b",
    firstName: "Kevin",
    lastName: "Moore",
    email: "kevin@insuretech.co",
    avatarUrl: "/professional-man-older.jpg",
    linkedInUrl: "https://linkedin.com/in/kevinmoore",
    company: {
      name: "InsureTech Pro",
      role: "Head of Marketing",
      website: "insuretech.co",
      stage: "Series C",
      headcount: "150-200",
      industry: "InsurTech",
    },
    status: "active",
    joinedAt: "2024-02-01T00:00:00Z",
    renewalDate: "2026-02-01T00:00:00Z",
    riskTier: "green",
    riskScore: 14,
    engagementScore: 86,
    lastEngagementAt: "2025-12-28T00:00:00Z",
    contactState: "open",
    lastContactedAt: "2025-12-26T00:00:00Z",
    lastValueDropAt: "2025-12-26T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-02-05T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2024-02-08T00:00:00Z",
      introPackDelivered: true,
      profileVerified: true,
    },
    tags: ["regulated", "enterprise", "traditional"],
    createdAt: "2024-02-01T00:00:00Z",
    updatedAt: "2025-12-28T00:00:00Z",
  },
  {
    id: "mem_019",
    tenantId: "b2b",
    firstName: "Samantha",
    lastName: "Davis",
    email: "samantha@mediatech.io",
    avatarUrl: "/professional-woman-african-american.jpg",
    linkedInUrl: "https://linkedin.com/in/samanthadavis",
    company: {
      name: "MediaTech",
      role: "VP Growth",
      website: "mediatech.io",
      stage: "Series A",
      headcount: "45-65",
      industry: "Media Tech",
    },
    status: "active",
    joinedAt: "2024-08-01T00:00:00Z",
    renewalDate: "2026-02-01T00:00:00Z",
    riskTier: "yellow",
    riskScore: 38,
    engagementScore: 58,
    lastEngagementAt: "2025-12-16T00:00:00Z",
    contactState: "open",
    lastContactedAt: "2025-12-12T00:00:00Z",
    lastValueDropAt: "2025-12-08T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-08-05T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2024-08-10T00:00:00Z",
      introPackDelivered: true,
      profileVerified: true,
    },
    tags: ["content", "advertising", "creator-economy"],
    createdAt: "2024-08-01T00:00:00Z",
    updatedAt: "2025-12-16T00:00:00Z",
  },
  {
    id: "mem_020",
    tenantId: "b2b",
    firstName: "Brian",
    lastName: "Jackson",
    email: "brian@supplychain.io",
    avatarUrl: "/professional-man-casual.jpg",
    linkedInUrl: "https://linkedin.com/in/brianjackson",
    company: {
      name: "SupplyChain AI",
      role: "CMO",
      website: "supplychain.io",
      stage: "Series B",
      headcount: "80-120",
      industry: "Supply Chain",
    },
    status: "active",
    joinedAt: "2024-05-01T00:00:00Z",
    renewalDate: "2026-05-01T00:00:00Z",
    riskTier: "green",
    riskScore: 16,
    engagementScore: 84,
    lastEngagementAt: "2025-12-29T00:00:00Z",
    contactState: "open",
    lastContactedAt: "2025-12-27T00:00:00Z",
    lastValueDropAt: "2025-12-27T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-05-05T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2024-05-08T00:00:00Z",
      introPackDelivered: true,
      profileVerified: true,
    },
    tags: ["ai", "enterprise", "operations"],
    createdAt: "2024-05-01T00:00:00Z",
    updatedAt: "2025-12-29T00:00:00Z",
  },
  {
    id: "mem_021",
    tenantId: "b2b",
    firstName: "Diana",
    lastName: "Ross",
    email: "diana@biotech.io",
    avatarUrl: "/professional-woman-scientist.png",
    linkedInUrl: "https://linkedin.com/in/dianaross",
    company: {
      name: "BioTech Innovations",
      role: "Head of Marketing",
      website: "biotech.io",
      stage: "Series A",
      headcount: "30-50",
      industry: "BioTech",
    },
    status: "lead",
    joinedAt: "2025-12-15T00:00:00Z",
    riskTier: "green",
    riskScore: 25,
    engagementScore: 0,
    contactState: "open",
    onboarding: {
      intakeCompleted: false,
      welcomeCallCompleted: false,
      introPackDelivered: false,
      profileVerified: false,
    },
    tags: ["new-member", "life-sciences", "regulated"],
    createdAt: "2025-12-15T00:00:00Z",
    updatedAt: "2025-12-15T00:00:00Z",
  },
  {
    id: "mem_022",
    tenantId: "b2b",
    firstName: "Steven",
    lastName: "Clark",
    email: "steven@constructtech.co",
    avatarUrl: "/professional-man-construction.jpg",
    linkedInUrl: "https://linkedin.com/in/stevenclark",
    company: {
      name: "ConstructTech",
      role: "VP Marketing",
      website: "constructtech.co",
      stage: "Series B",
      headcount: "100-150",
      industry: "Construction Tech",
    },
    status: "active",
    joinedAt: "2024-07-01T00:00:00Z",
    renewalDate: "2026-01-01T00:00:00Z",
    riskTier: "red",
    riskScore: 65,
    engagementScore: 32,
    lastEngagementAt: "2025-11-25T00:00:00Z",
    contactState: "muted",
    lastContactedAt: "2025-12-20T00:00:00Z",
    lastValueDropAt: "2025-11-01T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-07-05T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2024-07-10T00:00:00Z",
      introPackDelivered: true,
      profileVerified: false,
    },
    tags: ["construction", "field-ops", "enterprise"],
    createdAt: "2024-07-01T00:00:00Z",
    updatedAt: "2025-12-20T00:00:00Z",
  },
  {
    id: "mem_023",
    tenantId: "b2b",
    firstName: "Michelle",
    lastName: "Turner",
    email: "michelle@foodtech.io",
    avatarUrl: "/professional-woman-chef.jpg",
    linkedInUrl: "https://linkedin.com/in/michelleturner",
    company: {
      name: "FoodTech Pro",
      role: "CMO",
      website: "foodtech.io",
      stage: "Series A",
      headcount: "40-60",
      industry: "Food Tech",
    },
    status: "accepted",
    joinedAt: "2025-12-20T00:00:00Z",
    renewalDate: "2026-06-20T00:00:00Z",
    riskTier: "green",
    riskScore: 20,
    engagementScore: 0,
    contactState: "open",
    onboarding: {
      intakeCompleted: false,
      welcomeCallCompleted: false,
      introPackDelivered: false,
      profileVerified: false,
    },
    tags: ["new-member", "food-beverage", "d2c"],
    createdAt: "2025-12-20T00:00:00Z",
    updatedAt: "2025-12-20T00:00:00Z",
  },
  {
    id: "mem_024",
    tenantId: "b2b",
    firstName: "Andrew",
    lastName: "Wright",
    email: "andrew@sportstech.co",
    avatarUrl: "/professional-man-athletic.jpg",
    linkedInUrl: "https://linkedin.com/in/andrewwright",
    company: {
      name: "SportsTech",
      role: "Head of Growth",
      website: "sportstech.co",
      stage: "Series B",
      headcount: "55-80",
      industry: "Sports Tech",
    },
    status: "churned",
    joinedAt: "2023-06-01T00:00:00Z",
    riskTier: "red",
    riskScore: 100,
    engagementScore: 5,
    lastEngagementAt: "2025-05-15T00:00:00Z",
    contactState: "closed",
    lastContactedAt: "2025-06-01T00:00:00Z",
    lastValueDropAt: "2025-04-01T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2023-06-05T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2023-06-10T00:00:00Z",
      introPackDelivered: true,
      profileVerified: true,
    },
    tags: ["churned", "sports", "media"],
    createdAt: "2023-06-01T00:00:00Z",
    updatedAt: "2025-06-01T00:00:00Z",
  },
  {
    id: "mem_025",
    tenantId: "b2b",
    firstName: "Patricia",
    lastName: "Adams",
    email: "patricia@eventtech.io",
    avatarUrl: "/professional-woman-events.jpg",
    linkedInUrl: "https://linkedin.com/in/patriciaadams",
    company: {
      name: "EventTech Pro",
      role: "VP Marketing",
      website: "eventtech.io",
      stage: "Series A",
      headcount: "25-40",
      industry: "Event Tech",
    },
    status: "paused",
    joinedAt: "2024-03-10T00:00:00Z",
    renewalDate: "2026-03-10T00:00:00Z",
    riskTier: "yellow",
    riskScore: 55,
    engagementScore: 40,
    lastEngagementAt: "2025-10-01T00:00:00Z",
    contactState: "closed",
    lastContactedAt: "2025-11-01T00:00:00Z",
    lastValueDropAt: "2025-09-15T00:00:00Z",
    onboarding: {
      intakeCompleted: true,
      intakeCompletedAt: "2024-03-15T00:00:00Z",
      welcomeCallCompleted: true,
      welcomeCallAt: "2024-03-20T00:00:00Z",
      introPackDelivered: true,
      profileVerified: true,
    },
    tags: ["paused", "events", "hybrid"],
    notes: "On parental leave until March 2026",
    createdAt: "2024-03-10T00:00:00Z",
    updatedAt: "2025-11-01T00:00:00Z",
  },
]

// ============================================================================
// FACTS
// ============================================================================

export const mockFacts: Fact[] = [
  // Sarah Chen facts
  {
    id: "fact_001",
    memberId: "mem_001",
    category: "goal",
    key: "Primary Goal",
    value: "Scale enterprise pipeline from $5M to $15M ARR",
    confidence: 95,
    provenance: "intake",
    evidence: {
      source: "Intake Form",
      snippet: "Our main objective is to 3x our enterprise pipeline this year",
      capturedAt: "2024-03-18T00:00:00Z",
    },
    verifiedAt: "2024-03-20T00:00:00Z",
    verifiedBy: "admin",
    createdAt: "2024-03-18T00:00:00Z",
    updatedAt: "2024-03-20T00:00:00Z",
  },
  {
    id: "fact_002",
    memberId: "mem_001",
    category: "bottleneck",
    key: "Current Challenge",
    value: "Content production bottleneck - need to 5x output",
    confidence: 88,
    provenance: "slack",
    evidence: {
      source: "Slack #general",
      snippet: "Really struggling to keep up with content demands for all our campaigns",
      capturedAt: "2025-12-15T00:00:00Z",
    },
    createdAt: "2025-12-15T00:00:00Z",
    updatedAt: "2025-12-15T00:00:00Z",
  },
  {
    id: "fact_003",
    memberId: "mem_001",
    category: "stack",
    key: "Marketing Stack",
    value: "HubSpot, 6sense, Outreach, Gong, Figma",
    confidence: 92,
    provenance: "survey",
    evidence: {
      source: "Quarterly Survey",
      capturedAt: "2025-10-01T00:00:00Z",
    },
    createdAt: "2025-10-01T00:00:00Z",
    updatedAt: "2025-10-01T00:00:00Z",
  },
  {
    id: "fact_004",
    memberId: "mem_001",
    category: "hiring",
    key: "Hiring Plans",
    value: "Looking for Head of Content, 2 demand gen managers",
    confidence: 85,
    provenance: "call",
    evidence: {
      source: "Welcome Call Recording",
      snippet: "Planning to expand the team significantly in Q1",
      capturedAt: "2024-03-20T00:00:00Z",
    },
    createdAt: "2024-03-20T00:00:00Z",
    updatedAt: "2024-03-20T00:00:00Z",
  },
  // Marcus Johnson facts
  {
    id: "fact_005",
    memberId: "mem_002",
    category: "goal",
    key: "Primary Goal",
    value: "Build PLG motion alongside existing sales-led approach",
    confidence: 90,
    provenance: "intake",
    evidence: {
      source: "Intake Form",
      capturedAt: "2024-06-05T00:00:00Z",
    },
    createdAt: "2024-06-05T00:00:00Z",
    updatedAt: "2024-06-05T00:00:00Z",
  },
  {
    id: "fact_006",
    memberId: "mem_002",
    category: "bottleneck",
    key: "Current Challenge",
    value: "Struggling with attribution across PLG and sales",
    confidence: 82,
    provenance: "slack",
    evidence: {
      source: "Slack DM",
      snippet: "Attribution is killing me right now",
      capturedAt: "2025-11-20T00:00:00Z",
    },
    createdAt: "2025-11-20T00:00:00Z",
    updatedAt: "2025-11-20T00:00:00Z",
  },
  // Elena Rodriguez facts
  {
    id: "fact_007",
    memberId: "mem_003",
    category: "goal",
    key: "Primary Goal",
    value: "Get first 100 enterprise customers",
    confidence: 88,
    provenance: "intake",
    evidence: {
      source: "Intake Form",
      capturedAt: "2024-09-15T00:00:00Z",
    },
    createdAt: "2024-09-15T00:00:00Z",
    updatedAt: "2024-09-15T00:00:00Z",
  },
  {
    id: "fact_008",
    memberId: "mem_003",
    category: "constraint",
    key: "Budget Constraint",
    value: "Limited marketing budget - under $50k/month",
    confidence: 75,
    provenance: "survey",
    evidence: {
      source: "Quarterly Survey",
      capturedAt: "2025-09-01T00:00:00Z",
    },
    createdAt: "2025-09-01T00:00:00Z",
    updatedAt: "2025-09-01T00:00:00Z",
  },
  // David Kim facts
  {
    id: "fact_009",
    memberId: "mem_004",
    category: "goal",
    key: "Primary Goal",
    value: "Build developer community to 100k members",
    confidence: 95,
    provenance: "intake",
    evidence: {
      source: "Intake Form",
      capturedAt: "2024-01-22T00:00:00Z",
    },
    verifiedAt: "2024-01-25T00:00:00Z",
    verifiedBy: "admin",
    createdAt: "2024-01-22T00:00:00Z",
    updatedAt: "2024-01-25T00:00:00Z",
  },
  {
    id: "fact_010",
    memberId: "mem_004",
    category: "background",
    key: "Previous Role",
    value: "Former DevRel lead at Stripe",
    confidence: 100,
    provenance: "linkedin",
    evidence: {
      source: "LinkedIn",
      url: "https://linkedin.com/in/davidkim",
      capturedAt: "2024-01-22T00:00:00Z",
    },
    createdAt: "2024-01-22T00:00:00Z",
    updatedAt: "2024-01-22T00:00:00Z",
  },
]

// ============================================================================
// EXTERNAL SIGNALS
// ============================================================================

export const mockSignals: ExternalSignal[] = [
  {
    id: "sig_001",
    memberId: "mem_001",
    source: "linkedin",
    type: "hiring",
    whatHappened: "TechScale posted 3 new marketing roles on LinkedIn",
    impliedNeeds: ["Hiring support", "Team scaling advice", "Org structure guidance"],
    tags: ["hiring", "growth", "team"],
    urgency: 6,
    confidence: 95,
    evidence: {
      url: "https://linkedin.com/company/techscale/jobs",
      snippet: "Marketing Manager, Content Lead, Demand Gen Specialist",
    },
    processedAt: "2025-12-28T00:00:00Z",
    createdAt: "2025-12-28T00:00:00Z",
  },
  {
    id: "sig_002",
    memberId: "mem_002",
    source: "slack",
    type: "pain_point",
    whatHappened: "Marcus mentioned struggling with board prep in #general",
    impliedNeeds: ["Board deck templates", "Metrics guidance", "Peer advice"],
    tags: ["board", "metrics", "stress"],
    urgency: 8,
    confidence: 88,
    evidence: {
      snippet:
        "Board meeting in 2 weeks and I still havent figured out how to present our PLG metrics alongside sales...",
    },
    processedAt: "2025-12-27T00:00:00Z",
    createdAt: "2025-12-27T00:00:00Z",
  },
  {
    id: "sig_003",
    memberId: "mem_003",
    source: "careers",
    type: "contraction",
    whatHappened: "DataFlow AI removed 5 job postings from their careers page",
    impliedNeeds: ["Support during downturn", "Efficiency playbooks", "Check-in call"],
    tags: ["hiring-freeze", "budget", "concern"],
    urgency: 9,
    confidence: 75,
    evidence: {
      url: "https://dataflow.ai/careers",
      snippet: "Reduced from 8 to 3 open positions",
    },
    processedAt: "2025-12-26T00:00:00Z",
    createdAt: "2025-12-26T00:00:00Z",
  },
  {
    id: "sig_004",
    memberId: "mem_004",
    source: "x",
    type: "milestone",
    whatHappened: "David announced CloudNative hit 50k GitHub stars",
    impliedNeeds: ["Congratulations", "Case study opportunity", "Community growth tips"],
    tags: ["win", "community", "growth"],
    urgency: 5,
    confidence: 100,
    evidence: {
      url: "https://x.com/davidkim/status/123456",
      snippet: "Incredible milestone - CloudNative just hit 50k stars on GitHub! Thank you to our amazing community.",
    },
    processedAt: "2025-12-25T00:00:00Z",
    createdAt: "2025-12-25T00:00:00Z",
  },
  {
    id: "sig_005",
    memberId: "mem_007",
    source: "survey",
    type: "sentiment",
    whatHappened: "Priya rated community value as 3/10 in quarterly survey",
    impliedNeeds: ["Urgent follow-up", "Value delivery", "Retention intervention"],
    tags: ["churn-risk", "dissatisfied", "urgent"],
    urgency: 10,
    confidence: 100,
    evidence: {
      snippet:
        'Survey response: "Haven\'t found the right connections yet. Feeling like this might not be the right fit."',
    },
    processedAt: "2025-12-20T00:00:00Z",
    createdAt: "2025-12-20T00:00:00Z",
  },
  {
    id: "sig_006",
    memberId: "mem_014",
    source: "indeed",
    type: "hiring",
    whatHappened: "RetailTech posting for CMO replacement on Indeed",
    impliedNeeds: ["Check on Tom's status", "Transition support"],
    tags: ["leadership-change", "concern", "urgent"],
    urgency: 9,
    confidence: 80,
    evidence: {
      url: "https://indeed.com/jobs/retailtech-cmo",
      snippet: "Chief Marketing Officer - RetailTech - Full-time",
    },
    processedAt: "2025-12-22T00:00:00Z",
    createdAt: "2025-12-22T00:00:00Z",
  },
  {
    id: "sig_007",
    memberId: "mem_006",
    source: "call",
    type: "request",
    whatHappened: "James asked about fintech compliance marketing in mastermind",
    impliedNeeds: ["Compliance playbook", "Regulated industry intros"],
    tags: ["compliance", "fintech", "request"],
    urgency: 6,
    confidence: 92,
    evidence: {
      snippet: "How are others handling FINRA requirements for marketing claims?",
    },
    processedAt: "2025-12-24T00:00:00Z",
    createdAt: "2025-12-24T00:00:00Z",
  },
  {
    id: "sig_008",
    memberId: "mem_008",
    source: "linkedin",
    type: "funding",
    whatHappened: "SecurityFirst announced $40M Series C",
    impliedNeeds: ["Congratulations", "Scaling resources", "Enterprise playbooks"],
    tags: ["funding", "growth", "celebration"],
    urgency: 5,
    confidence: 100,
    evidence: {
      url: "https://linkedin.com/posts/securityfirst-series-c",
      snippet: "Excited to announce our $40M Series C led by Accel",
    },
    processedAt: "2025-12-23T00:00:00Z",
    createdAt: "2025-12-23T00:00:00Z",
  },
]

// ============================================================================
// OPPORTUNITIES
// ============================================================================

export const mockOpportunities: OpportunityItem[] = [
  {
    id: "opp_001",
    memberId: "mem_001",
    summary: "Sarah is scaling content team - opportunity for intro to content agencies",
    tags: ["content", "hiring", "agencies"],
    urgency: 7,
    confidence: 88,
    source: "linkedin",
    signalId: "sig_001",
    recommendedActions: [
      {
        id: "act_001",
        type: "intro",
        title: "Intro to Content Velocity (agency)",
        rationale: "Content Velocity specializes in B2B SaaS content at scale, perfect match for Sarah's needs",
        impactScore: 85,
        evidence: {
          factIds: ["fact_002"],
          signalIds: ["sig_001"],
          description: "Based on content bottleneck and hiring signals",
        },
        createdAt: "2025-12-28T00:00:00Z",
      },
      {
        id: "act_002",
        type: "resource",
        title: 'Share "Scaling Content Teams" playbook',
        rationale: "Directly addresses her current challenge with actionable frameworks",
        impactScore: 72,
        evidence: {
          factIds: ["fact_002"],
          description: "Matches stated bottleneck",
        },
        relatedResourceId: "res_001",
        createdAt: "2025-12-28T00:00:00Z",
      },
    ],
    dismissed: false,
    createdAt: "2025-12-28T00:00:00Z",
  },
  {
    id: "opp_002",
    memberId: "mem_002",
    summary: "Marcus needs help with board prep and PLG metrics",
    tags: ["board", "metrics", "plg", "urgent"],
    urgency: 9,
    confidence: 92,
    source: "slack",
    signalId: "sig_002",
    recommendedActions: [
      {
        id: "act_003",
        type: "resource",
        title: 'Share "PLG Metrics for Boards" template',
        rationale: "Exactly what Marcus needs for his upcoming board meeting",
        impactScore: 95,
        evidence: {
          signalIds: ["sig_002"],
          description: "Direct request from Slack",
        },
        relatedResourceId: "res_002",
        createdAt: "2025-12-27T00:00:00Z",
      },
      {
        id: "act_004",
        type: "intro",
        title: "Intro to David Kim (expert in PLG metrics)",
        rationale: "David has successfully presented PLG metrics to boards multiple times",
        impactScore: 88,
        evidence: {
          factIds: ["fact_009"],
          signalIds: ["sig_002"],
          description: "David is expert in this area",
        },
        relatedMemberId: "mem_004",
        createdAt: "2025-12-27T00:00:00Z",
      },
    ],
    dismissed: false,
    createdAt: "2025-12-27T00:00:00Z",
  },
  {
    id: "opp_003",
    memberId: "mem_003",
    summary: "Elena's company may be struggling - signals of contraction",
    tags: ["churn-risk", "support", "urgent"],
    urgency: 10,
    confidence: 78,
    source: "careers",
    signalId: "sig_003",
    recommendedActions: [
      {
        id: "act_005",
        type: "check_in",
        title: "Proactive check-in call",
        rationale: "Early intervention could prevent churn and provide needed support",
        impactScore: 92,
        evidence: {
          signalIds: ["sig_003"],
          description: "Hiring freeze signals potential challenges",
        },
        suggestedContent:
          "Hey Elena, wanted to check in and see how things are going. Happy to chat if you need a sounding board.",
        createdAt: "2025-12-26T00:00:00Z",
      },
      {
        id: "act_006",
        type: "resource",
        title: 'Share "Doing More with Less" playbook',
        rationale: "Budget-conscious marketing strategies for constrained teams",
        impactScore: 78,
        evidence: {
          factIds: ["fact_008"],
          signalIds: ["sig_003"],
          description: "Known budget constraints plus contraction signals",
        },
        relatedResourceId: "res_003",
        createdAt: "2025-12-26T00:00:00Z",
      },
    ],
    dismissed: false,
    createdAt: "2025-12-26T00:00:00Z",
  },
  {
    id: "opp_004",
    memberId: "mem_004",
    summary: "David hit major milestone - celebration and case study opportunity",
    tags: ["celebration", "case-study", "community"],
    urgency: 5,
    confidence: 100,
    source: "x",
    signalId: "sig_004",
    recommendedActions: [
      {
        id: "act_007",
        type: "check_in",
        title: "Congratulate on 50k GitHub stars",
        rationale: "Celebrate wins and strengthen relationship",
        impactScore: 65,
        evidence: {
          signalIds: ["sig_004"],
          description: "Public milestone announcement",
        },
        suggestedContent: "Huge congrats on hitting 50k stars! That's an incredible milestone for CloudNative.",
        createdAt: "2025-12-25T00:00:00Z",
      },
    ],
    dismissed: false,
    createdAt: "2025-12-25T00:00:00Z",
  },
  {
    id: "opp_005",
    memberId: "mem_007",
    summary: "Priya rated community low - urgent retention intervention needed",
    tags: ["churn-risk", "retention", "critical"],
    urgency: 10,
    confidence: 100,
    source: "survey",
    signalId: "sig_005",
    recommendedActions: [
      {
        id: "act_008",
        type: "intro",
        title: "Targeted intro to 3 healthtech CMOs",
        rationale: "Address her specific need for relevant connections",
        impactScore: 95,
        evidence: {
          signalIds: ["sig_005"],
          description: "Survey indicates lack of relevant connections",
        },
        createdAt: "2025-12-20T00:00:00Z",
      },
      {
        id: "act_009",
        type: "check_in",
        title: "Personal outreach from community lead",
        rationale: "High-touch intervention for high-risk member",
        impactScore: 90,
        evidence: {
          signalIds: ["sig_005"],
          description: "Low satisfaction score requires immediate action",
        },
        suggestedContent:
          "Hi Priya, I saw your survey feedback and wanted to reach out personally. I'd love to understand what would make your experience better and make some targeted intros.",
        createdAt: "2025-12-20T00:00:00Z",
      },
    ],
    dismissed: false,
    createdAt: "2025-12-20T00:00:00Z",
  },
]

// ============================================================================
// MESSAGE DRAFTS
// ============================================================================

export const mockDrafts: MessageDraft[] = [
  {
    id: "draft_001",
    memberId: "mem_001",
    actionType: "resource",
    content:
      "Hey Sarah! Saw you're scaling up the content team - congrats on the growth! Wanted to share our \"Scaling Content Teams\" playbook that a few members have found really helpful. It covers hiring frameworks, agency vs in-house decisions, and workflow optimization. Let me know if you'd like to chat through any of it!",
    impactScore: 72,
    autosendEligible: true,
    blockedReasons: [],
    sendRecommendation: "send",
    status: "pending",
    generatedFromOpportunityId: "opp_001",
    generatedFromActionId: "act_002",
    createdAt: "2025-12-28T10:00:00Z",
  },
  {
    id: "draft_002",
    memberId: "mem_002",
    actionType: "resource",
    content:
      "Hey Marcus! Caught your message about board prep - totally get it, presenting PLG alongside sales is tricky. I've got a \"PLG Metrics for Boards\" template that might help. It's got frameworks for blended attribution and how to tell the story to board members used to traditional sales metrics. Want me to send it over?",
    impactScore: 95,
    autosendEligible: true,
    blockedReasons: [],
    sendRecommendation: "send",
    status: "pending",
    generatedFromOpportunityId: "opp_002",
    generatedFromActionId: "act_003",
    createdAt: "2025-12-27T14:00:00Z",
  },
  {
    id: "draft_003",
    memberId: "mem_003",
    actionType: "check_in",
    content:
      "Hey Elena, wanted to check in and see how things are going at DataFlow. I know the AI space is moving fast - happy to chat if you need a sounding board or want to brainstorm anything. Also have some resources on efficient marketing strategies if helpful. No pressure, just wanted you to know we're here!",
    impactScore: 92,
    autosendEligible: false,
    blockedReasons: ["Last contact was less than 7 days ago", "Member has low engagement score"],
    sendRecommendation: "review",
    status: "pending",
    generatedFromOpportunityId: "opp_003",
    generatedFromActionId: "act_005",
    createdAt: "2025-12-26T16:00:00Z",
  },
  {
    id: "draft_004",
    memberId: "mem_007",
    actionType: "intro",
    content:
      "Hi Priya! I saw your survey feedback and wanted to reach out personally. I've identified 3 healthtech CMOs in the community who I think would be really valuable connections for you:\n\n1. James Wilson (FinTech Solutions) - dealt with similar HIPAA compliance challenges\n2. Kevin Moore (InsureTech Pro) - extensive regulated industry experience\n3. Diana Ross (BioTech Innovations) - just joined but has great life sciences background\n\nWould any of these intros be helpful? Happy to make warm introductions this week.",
    impactScore: 95,
    autosendEligible: false,
    blockedReasons: ["Contact state is closed"],
    sendRecommendation: "hold",
    status: "pending",
    generatedFromOpportunityId: "opp_005",
    generatedFromActionId: "act_008",
    createdAt: "2025-12-20T18:00:00Z",
  },
  {
    id: "draft_005",
    memberId: "mem_004",
    actionType: "check_in",
    content:
      "Huge congrats on hitting 50k GitHub stars, David! That's an incredible milestone for CloudNative and a testament to the amazing community you've built. Would love to hear how you got there - might make for a great case study or workshop topic for the club if you're interested!",
    impactScore: 65,
    autosendEligible: true,
    blockedReasons: [],
    sendRecommendation: "send",
    status: "pending",
    generatedFromOpportunityId: "opp_004",
    generatedFromActionId: "act_007",
    createdAt: "2025-12-25T12:00:00Z",
  },
]

// ============================================================================
// INTROS
// ============================================================================

export const mockIntroSuggestions: IntroSuggestion[] = [
  {
    id: "intro_sug_001",
    memberAId: "mem_001",
    memberBId: "mem_008",
    rationale: "Both focusing on enterprise marketing, Michael has experience Sarah needs with channel partnerships",
    impactScore: 82,
    matchingFactIds: ["fact_001", "fact_004"],
    dismissed: false,
    createdAt: "2025-12-28T00:00:00Z",
  },
  {
    id: "intro_sug_002",
    memberAId: "mem_002",
    memberBId: "mem_004",
    rationale: "David can help Marcus with PLG metrics presentation to board",
    impactScore: 90,
    matchingFactIds: ["fact_005", "fact_009"],
    dismissed: false,
    createdAt: "2025-12-27T00:00:00Z",
  },
  {
    id: "intro_sug_003",
    memberAId: "mem_007",
    memberBId: "mem_006",
    rationale:
      "Both in regulated industries (healthcare/fintech), James has compliance marketing experience Priya needs",
    impactScore: 88,
    matchingFactIds: [],
    dismissed: false,
    createdAt: "2025-12-20T00:00:00Z",
  },
]

export const mockIntroRecords: IntroRecord[] = [
  {
    id: "intro_001",
    memberAId: "mem_001",
    memberBId: "mem_010",
    status: "completed",
    messageToA:
      "Sarah, meet Robert from LogisticsPro - he's built an incredible enterprise marketing org and has great insights on field marketing.",
    messageToB:
      "Robert, meet Sarah from TechScale - she's scaling their enterprise motion and could use your expertise.",
    outcomeA: {
      rating: 9,
      feedback: "Great intro! Robert had amazing advice on enterprise events.",
    },
    outcomeB: {
      rating: 8,
      feedback: "Good connection, looking forward to following up.",
    },
    createdBy: "admin",
    createdAt: "2025-12-15T00:00:00Z",
    completedAt: "2025-12-22T00:00:00Z",
  },
  {
    id: "intro_002",
    memberAId: "mem_004",
    memberBId: "mem_012",
    status: "pending",
    messageToA:
      "David, meet Chris from PropTech Solutions - he's building developer tools for real estate and could use community building advice.",
    messageToB: "Chris, meet David from CloudNative - he literally wrote the book on developer community building.",
    createdBy: "admin",
    createdAt: "2025-12-26T00:00:00Z",
  },
]

// ============================================================================
// PERKS
// ============================================================================

export const mockPerks: Perk[] = [
  {
    id: "perk_001",
    tenantId: "b2b",
    name: "HubSpot Startup Program",
    description: "90% off HubSpot for 12 months, plus dedicated onboarding support",
    category: "saas",
    partnerName: "HubSpot",
    partnerLogo: "/hubspot-logo.png",
    value: "$15,000",
    url: "https://hubspot.com/startup-program",
    active: true,
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "perk_002",
    tenantId: "b2b",
    name: "Figma Organization Plan",
    description: "Free Figma Organization plan for 12 months",
    category: "saas",
    partnerName: "Figma",
    partnerLogo: "/figma-logo.png",
    value: "$5,400",
    url: "https://figma.com",
    active: true,
    createdAt: "2024-02-01T00:00:00Z",
  },
  {
    id: "perk_003",
    tenantId: "b2b",
    name: "6sense ABM Platform",
    description: "50% off first year of 6sense, plus implementation support",
    category: "saas",
    partnerName: "6sense",
    partnerLogo: "/6sense-logo.jpg",
    value: "$25,000",
    url: "https://6sense.com",
    active: true,
    createdAt: "2024-03-01T00:00:00Z",
  },
  {
    id: "perk_004",
    tenantId: "b2b",
    name: "Executive Coaching Session",
    description: "Free 1-hour executive coaching session with leadership coach",
    category: "service",
    partnerName: "Leadership Labs",
    value: "$500",
    active: true,
    createdAt: "2024-04-01T00:00:00Z",
  },
  {
    id: "perk_005",
    tenantId: "b2b",
    name: "SaaStr Annual VIP Pass",
    description: "Complimentary VIP pass to SaaStr Annual conference",
    category: "event",
    partnerName: "SaaStr",
    partnerLogo: "/saastr-logo.jpg",
    value: "$2,500",
    expiresAt: "2026-09-01T00:00:00Z",
    active: true,
    createdAt: "2024-05-01T00:00:00Z",
  },
]

export const mockPerkRecommendations: PerkRecommendation[] = [
  {
    id: "perk_rec_001",
    memberId: "mem_001",
    perkId: "perk_003",
    rationale: "Sarah mentioned needing ABM tools for enterprise pipeline - 6sense is perfect match",
    impactScore: 88,
    matchingFactIds: ["fact_001", "fact_003"],
    dismissed: false,
    createdAt: "2025-12-28T00:00:00Z",
  },
  {
    id: "perk_rec_002",
    memberId: "mem_003",
    perkId: "perk_001",
    rationale: "Elena needs marketing automation but has budget constraints - HubSpot startup discount is ideal",
    impactScore: 92,
    matchingFactIds: ["fact_007", "fact_008"],
    dismissed: false,
    createdAt: "2025-12-26T00:00:00Z",
  },
]

export const mockPerkPartnerApplications: PerkPartnerApplication[] = [
  {
    id: "partner_app_001",
    tenantId: "b2b",
    companyName: "ContentAI",
    contactName: "Alex Rivera",
    contactEmail: "alex@contentai.com",
    perkDescription: "3 months free AI content generation, valued at $3,000",
    status: "pending",
    createdAt: "2025-12-27T00:00:00Z",
  },
  {
    id: "partner_app_002",
    tenantId: "b2b",
    companyName: "DataStudio",
    contactName: "Jamie Chen",
    contactEmail: "jamie@datastudio.io",
    perkDescription: "50% off annual analytics platform subscription",
    status: "approved",
    reviewedBy: "admin",
    reviewedAt: "2025-12-20T00:00:00Z",
    createdAt: "2025-12-15T00:00:00Z",
  },
]

// ============================================================================
// PROGRAMMING
// ============================================================================

export const mockMastermindGroups: MastermindGroup[] = [
  {
    id: "mm_001",
    tenantId: "b2b",
    name: "Enterprise Growth",
    theme: "Scaling enterprise sales and marketing alignment",
    memberIds: ["mem_001", "mem_004", "mem_006", "mem_008", "mem_010"],
    leaderId: "mem_004",
    nextSessionAt: "2026-01-08T17:00:00Z",
    rotationSchedule: ["mem_004", "mem_001", "mem_008", "mem_006", "mem_010"],
    agendaDraft:
      "1. Hot seat: Sarah on content scaling\n2. Round robin: Q1 planning progress\n3. Resource share: Enterprise playbooks",
    followUpItems: [
      {
        memberId: "mem_001",
        item: "Share content agency recommendations",
        completed: false,
      },
      {
        memberId: "mem_008",
        item: "Post channel partner framework in Slack",
        dueAt: "2026-01-05T00:00:00Z",
        completed: true,
      },
    ],
    createdAt: "2024-06-01T00:00:00Z",
  },
  {
    id: "mm_002",
    tenantId: "b2b",
    name: "PLG Pioneers",
    theme: "Product-led growth strategies and metrics",
    memberIds: ["mem_002", "mem_009", "mem_011", "mem_016", "mem_019"],
    leaderId: "mem_002",
    nextSessionAt: "2026-01-10T16:00:00Z",
    rotationSchedule: ["mem_002", "mem_011", "mem_009", "mem_019", "mem_016"],
    followUpItems: [],
    createdAt: "2024-08-01T00:00:00Z",
  },
]

export const mockMonthlyAgendas: MonthlyClubAgenda[] = [
  {
    id: "agenda_001",
    tenantId: "b2b",
    month: "2026-01",
    themes: ["Q1 Planning", "AI in Marketing", "Budget Optimization"],
    template:
      "## January 2026 Programming\n\n### Week 1: Q1 Kickoff\n- Planning workshop\n- Goal setting session\n\n### Week 2: AI Deep Dive\n- AI tools workshop\n- Case study: AI-powered campaigns\n\n### Week 3: Budget Masters\n- Budget optimization tactics\n- ROI frameworks\n\n### Week 4: Networking\n- Monthly mixer\n- New member welcome",
    speakers: [
      { name: "Sarah Chen", topic: "Scaling Content with AI", confirmed: true },
      { name: "External: Kyle Poyar", topic: "PLG Pricing Strategies", confirmed: false },
    ],
    workshops: [
      { id: "ws_001", title: "Q1 Planning Workshop", status: "confirmed" },
      { id: "ws_002", title: "AI Tools Masterclass", status: "planned" },
    ],
    createdAt: "2025-12-15T00:00:00Z",
    updatedAt: "2025-12-28T00:00:00Z",
  },
]

export const mockWorkshopPlans: WorkshopPlan[] = [
  {
    id: "ws_plan_001",
    tenantId: "b2b",
    title: "Enterprise ABM Bootcamp",
    topic: "Building and executing ABM campaigns for enterprise deals",
    suggestedSpeakers: [
      { memberId: "mem_001", name: "Sarah Chen", rationale: "Has scaled ABM at TechScale" },
      { memberId: "mem_008", name: "Michael Brown", rationale: "Enterprise security marketing expert" },
      { name: "Jon Miller", rationale: "Founder of Engagio/Demandbase" },
    ],
    targetAudience: ["enterprise", "abm", "demand-gen"],
    status: "planning",
    createdAt: "2025-12-20T00:00:00Z",
  },
]

// ============================================================================
// RESOURCES
// ============================================================================

export const mockResources: KnowledgeResource[] = [
  {
    id: "res_001",
    tenantId: "b2b",
    title: "Scaling Content Teams Playbook",
    description: "Complete guide to hiring, structuring, and scaling content marketing teams from 1 to 20+ people",
    type: "playbook",
    tags: ["content", "hiring", "scaling", "team"],
    url: "https://notion.so/cmoclub/content-scaling",
    viewCount: 145,
    createdAt: "2024-06-01T00:00:00Z",
    updatedAt: "2025-11-15T00:00:00Z",
  },
  {
    id: "res_002",
    tenantId: "b2b",
    title: "PLG Metrics for Boards Template",
    description: "Board deck template for presenting product-led growth metrics alongside traditional sales metrics",
    type: "template",
    tags: ["plg", "board", "metrics", "presentation"],
    url: "https://notion.so/cmoclub/plg-board-template",
    viewCount: 89,
    createdAt: "2024-08-01T00:00:00Z",
    updatedAt: "2025-10-01T00:00:00Z",
  },
  {
    id: "res_003",
    tenantId: "b2b",
    title: "Doing More with Less: Efficient Marketing",
    description: "Strategies and frameworks for maximizing marketing impact with limited budgets and small teams",
    type: "playbook",
    tags: ["efficiency", "budget", "small-team", "optimization"],
    url: "https://notion.so/cmoclub/efficient-marketing",
    viewCount: 234,
    createdAt: "2024-04-01T00:00:00Z",
    updatedAt: "2025-12-01T00:00:00Z",
  },
  {
    id: "res_004",
    tenantId: "b2b",
    title: "Compliance Marketing in Regulated Industries",
    description: "How to navigate marketing restrictions in fintech, healthtech, and other regulated spaces",
    type: "playbook",
    tags: ["compliance", "fintech", "healthtech", "regulated"],
    url: "https://notion.so/cmoclub/compliance-marketing",
    viewCount: 67,
    createdAt: "2024-09-01T00:00:00Z",
    updatedAt: "2025-11-01T00:00:00Z",
  },
  {
    id: "res_005",
    tenantId: "b2b",
    title: "Developer Community Building Workshop Recording",
    description: "Recording from David Kim's workshop on building engaged developer communities",
    type: "recording",
    tags: ["devrel", "community", "developer-marketing"],
    url: "https://vimeo.com/cmoclub/dev-community",
    viewCount: 178,
    createdAt: "2025-03-01T00:00:00Z",
    updatedAt: "2025-03-01T00:00:00Z",
  },
]

// ============================================================================
// SURVEYS & PODS
// ============================================================================

export const mockSurveys: Survey[] = [
  {
    id: "survey_001",
    tenantId: "b2b",
    memberId: "mem_001",
    cadence: "quarterly",
    lastSentAt: "2025-10-01T00:00:00Z",
    lastCompletedAt: "2025-10-03T00:00:00Z",
    completionRate: 100,
    responses: [
      {
        questionId: "q1",
        question: "How valuable is your CMO Club membership?",
        answer: "9",
        sentiment: "positive",
      },
      {
        questionId: "q2",
        question: "What's your biggest current challenge?",
        answer: "Scaling content production while maintaining quality",
        sentiment: "neutral",
      },
    ],
  },
  {
    id: "survey_002",
    tenantId: "b2b",
    memberId: "mem_007",
    cadence: "quarterly",
    lastSentAt: "2025-12-15T00:00:00Z",
    lastCompletedAt: "2025-12-18T00:00:00Z",
    completionRate: 100,
    responses: [
      {
        questionId: "q1",
        question: "How valuable is your CMO Club membership?",
        answer: "3",
        sentiment: "negative",
        deltaSinceLast: "-4",
      },
      {
        questionId: "q2",
        question: "What's your biggest current challenge?",
        answer: "Haven't found relevant connections in healthtech",
        sentiment: "negative",
      },
    ],
  },
]

export const mockPods: Pod[] = [
  {
    id: "pod_001",
    tenantId: "b2b",
    name: "Q1 Accountability Pod",
    memberIds: ["mem_001", "mem_004", "mem_006", "mem_008"],
    monthlyGoalsPromptSent: true,
    monthlyGoalsReceived: ["mem_001", "mem_004", "mem_006"],
    receiptsShared: ["mem_001", "mem_004"],
    quietMemberIds: ["mem_008"],
    createdAt: "2025-12-01T00:00:00Z",
  },
]

// ============================================================================
// FORCED SUCCESS
// ============================================================================

export const mockForcedSuccessItems: ForcedSuccessItem[] = [
  {
    id: "fs_001",
    memberId: "mem_001",
    weekOf: "2025-W52",
    recommendedActionType: "resource",
    recommendedActions: [
      {
        id: "fs_act_001",
        type: "resource",
        title: "Share content scaling playbook",
        rationale: "Directly addresses current bottleneck",
        impactScore: 72,
        evidence: { description: "Based on recent signals" },
        createdAt: "2025-12-28T00:00:00Z",
      },
    ],
    deliveredActionType: "resource",
    deliveredAt: "2025-12-28T00:00:00Z",
    deliveredBy: "admin",
    draftId: "draft_001",
    blocked: false,
    createdAt: "2025-12-23T00:00:00Z",
  },
  {
    id: "fs_002",
    memberId: "mem_002",
    weekOf: "2025-W52",
    recommendedActionType: "resource",
    recommendedActions: [
      {
        id: "fs_act_002",
        type: "resource",
        title: "PLG metrics template",
        rationale: "Urgent need for board meeting",
        impactScore: 95,
        evidence: { description: "Direct request in Slack" },
        createdAt: "2025-12-27T00:00:00Z",
      },
    ],
    blocked: false,
    createdAt: "2025-12-23T00:00:00Z",
  },
  {
    id: "fs_003",
    memberId: "mem_003",
    weekOf: "2025-W52",
    recommendedActionType: "intro",
    recommendedActions: [
      {
        id: "fs_act_003",
        type: "intro",
        title: "Intro to early-stage CMOs",
        rationale: "Needs peer support during challenging time",
        impactScore: 85,
        evidence: { description: "Contraction signals detected" },
        createdAt: "2025-12-26T00:00:00Z",
      },
    ],
    blocked: true,
    blockedReason: "Member has low engagement - may not respond",
    createdAt: "2025-12-23T00:00:00Z",
  },
  {
    id: "fs_004",
    memberId: "mem_007",
    weekOf: "2025-W52",
    recommendedActionType: "intro",
    recommendedActions: [
      {
        id: "fs_act_004",
        type: "intro",
        title: "Targeted healthtech intros",
        rationale: "Critical retention intervention",
        impactScore: 95,
        evidence: { description: "Low survey score" },
        createdAt: "2025-12-20T00:00:00Z",
      },
    ],
    blocked: true,
    blockedReason: "Contact state is closed",
    createdAt: "2025-12-23T00:00:00Z",
  },
]

// ============================================================================
// AUDIT LOG
// ============================================================================

export const mockAuditLogs: AuditLogEntry[] = [
  {
    id: "audit_001",
    tenantId: "b2b",
    type: "draft_sent",
    actor: "admin",
    actorRole: "admin",
    memberId: "mem_001",
    details: {
      draftId: "draft_001",
      actionType: "resource",
      content: "Content scaling playbook shared",
    },
    createdAt: "2025-12-28T10:30:00Z",
  },
  {
    id: "audit_002",
    tenantId: "b2b",
    type: "contact_state_changed",
    actor: "admin",
    actorRole: "admin",
    memberId: "mem_007",
    details: {
      previousState: "open",
      newState: "closed",
      reason: "Member requested pause on outreach",
    },
    createdAt: "2025-12-28T09:00:00Z",
  },
  {
    id: "audit_003",
    tenantId: "b2b",
    type: "intro_created",
    actor: "admin",
    actorRole: "admin",
    memberId: "mem_004",
    details: {
      introId: "intro_002",
      memberBId: "mem_012",
      rationale: "Developer community building expertise match",
    },
    createdAt: "2025-12-26T14:00:00Z",
  },
  {
    id: "audit_004",
    tenantId: "b2b",
    type: "outcome_recorded",
    actor: "admin",
    actorRole: "admin",
    memberId: "mem_001",
    details: {
      interactionId: "int_001",
      rating: 9,
      feedback: "Great intro! Robert had amazing advice on enterprise events.",
    },
    createdAt: "2025-12-22T16:00:00Z",
  },
  {
    id: "audit_005",
    tenantId: "b2b",
    type: "forced_success_delivered",
    actor: "admin",
    actorRole: "admin",
    memberId: "mem_001",
    details: {
      forcedSuccessId: "fs_001",
      actionType: "resource",
      weekOf: "2025-W52",
    },
    createdAt: "2025-12-28T10:30:00Z",
  },
]

// ============================================================================
// AI CHAT
// ============================================================================

export const mockChatThreads: ChatThread[] = [
  {
    id: "chat_001",
    tenantId: "b2b",
    title: "Who needs attention this week?",
    messages: [
      {
        id: "msg_001",
        role: "user",
        content: "Who needs attention this week?",
        createdAt: "2025-12-28T09:00:00Z",
      },
      {
        id: "msg_002",
        role: "assistant",
        content:
          "Based on my analysis, here are the members who need attention this week:\n\n**Critical (Red Risk):**\n1. **Elena Rodriguez** (DataFlow AI) - Contraction signals detected, low engagement. Recommend proactive check-in.\n2. **Priya Patel** (HealthTech Co) - Rated community 3/10 in survey. Needs targeted intros.\n3. **Tom Harris** (RetailTech) - CMO replacement posting detected. Check on his status.\n\n**High Priority (Yellow Risk + Signals):**\n4. **Marcus Johnson** (GrowthEngine) - Struggling with board prep, needs PLG metrics help urgently.\n\nWould you like me to generate drafts for any of these?",
        evidence: {
          memberIds: ["mem_003", "mem_007", "mem_014", "mem_002"],
          signalIds: ["sig_003", "sig_005", "sig_006", "sig_002"],
        },
        suggestedActions: [
          {
            id: "sug_001",
            type: "check_in",
            title: "Check in with Elena",
            rationale: "Contraction signals need immediate attention",
            impactScore: 92,
            evidence: { description: "Hiring freeze detected" },
            createdAt: "2025-12-28T09:00:00Z",
          },
        ],
        createdAt: "2025-12-28T09:00:30Z",
      },
    ],
    createdAt: "2025-12-28T09:00:00Z",
    updatedAt: "2025-12-28T09:00:30Z",
  },
]

// ============================================================================
// PERSONA CLUSTERS
// ============================================================================

export const mockPersonaClusters: PersonaCluster[] = [
  {
    id: "cluster_001",
    tenantId: "b2b",
    name: "Enterprise Scalers",
    description: "Series B+ CMOs focused on enterprise sales and large deal cycles",
    memberIds: ["mem_001", "mem_004", "mem_006", "mem_008", "mem_010", "mem_013", "mem_017", "mem_018", "mem_020"],
    characteristics: ["Series B+", "Enterprise focus", "Large teams", "Sales alignment"],
    suggestedUses: ["Enterprise workshops", "ABM masterclasses", "Sales alignment intros"],
    createdAt: "2025-12-01T00:00:00Z",
  },
  {
    id: "cluster_002",
    tenantId: "b2b",
    name: "PLG Pioneers",
    description: "CMOs building product-led growth motions",
    memberIds: ["mem_002", "mem_009", "mem_011", "mem_016", "mem_019"],
    characteristics: ["PLG focus", "Self-serve", "Usage metrics", "Freemium"],
    suggestedUses: ["PLG workshops", "Attribution deep-dives", "PLG peer intros"],
    createdAt: "2025-12-01T00:00:00Z",
  },
  {
    id: "cluster_003",
    tenantId: "b2b",
    name: "Regulated Industry",
    description: "CMOs in fintech, healthtech, and other regulated spaces",
    memberIds: ["mem_006", "mem_007", "mem_013", "mem_018", "mem_021"],
    characteristics: ["Compliance-heavy", "Legal review", "HIPAA/FINRA", "Trust-building"],
    suggestedUses: ["Compliance playbooks", "Regulated industry intros", "Legal review workshops"],
    createdAt: "2025-12-01T00:00:00Z",
  },
]

// ============================================================================
// NOTIFICATIONS
// ============================================================================

export const mockNotifications: NotificationItem[] = [
  {
    id: "notif_001",
    type: "red_risk",
    title: "Red Risk: Elena Rodriguez",
    description: "Contraction signals detected at DataFlow AI",
    memberId: "mem_003",
    actionUrl: "/app/b2b/members/mem_003",
    read: false,
    createdAt: "2025-12-26T00:00:00Z",
  },
  {
    id: "notif_002",
    type: "escalation",
    title: "Low Survey Score: Priya Patel",
    description: "Rated community value 3/10 - requires intervention",
    memberId: "mem_007",
    actionUrl: "/app/b2b/members/mem_007",
    read: false,
    createdAt: "2025-12-20T00:00:00Z",
  },
  {
    id: "notif_003",
    type: "blocked_item",
    title: "Blocked: Forced Success for Elena",
    description: "Cannot deliver - member has low engagement",
    memberId: "mem_003",
    actionUrl: "/app/b2b/forced-success",
    read: true,
    createdAt: "2025-12-26T00:00:00Z",
  },
  {
    id: "notif_004",
    type: "renewal_alert",
    title: "Renewal in 30 days: Elena Rodriguez",
    description: "High-risk member renewal approaching",
    memberId: "mem_003",
    actionUrl: "/app/b2b/members/mem_003",
    read: false,
    createdAt: "2025-12-11T00:00:00Z",
  },
]

// ============================================================================
// INTERACTION LOGS & OUTCOMES
// ============================================================================

export const mockInteractionLogs: InteractionLog[] = [
  {
    id: "int_001",
    memberId: "mem_001",
    type: "intro",
    channel: "slack",
    summary: "Introduced Sarah to Robert Garcia for enterprise marketing advice",
    createdBy: "admin",
    createdAt: "2025-12-15T00:00:00Z",
  },
  {
    id: "int_002",
    memberId: "mem_001",
    type: "dm",
    channel: "slack",
    summary: "Shared content scaling playbook",
    draftId: "draft_001",
    createdBy: "admin",
    createdAt: "2025-12-28T10:30:00Z",
  },
]

export const mockOutcomeFeedback: OutcomeFeedback[] = [
  {
    id: "outcome_001",
    memberId: "mem_001",
    interactionId: "int_001",
    rating: 9,
    feedback: "Great intro! Robert had amazing advice on enterprise events.",
    escalated: false,
    createdAt: "2025-12-22T00:00:00Z",
  },
]

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

export function getMemberById(id: string): Member | undefined {
  return mockMembers.find((m) => m.id === id)
}

export function getMembersByTenant(tenantId: TenantId): Member[] {
  return mockMembers.filter((m) => m.tenantId === tenantId)
}

export function getMembersByRiskTier(tenantId: TenantId, tier: string): Member[] {
  return mockMembers.filter((m) => m.tenantId === tenantId && m.riskTier === tier)
}

export function getFactsByMember(memberId: string): Fact[] {
  return mockFacts.filter((f) => f.memberId === memberId)
}

export function getSignalsByMember(memberId: string): ExternalSignal[] {
  return mockSignals.filter((s) => s.memberId === memberId)
}

export function getOpportunitiesByMember(memberId: string): OpportunityItem[] {
  return mockOpportunities.filter((o) => o.memberId === memberId)
}

export function getDraftsByMember(memberId: string): MessageDraft[] {
  return mockDrafts.filter((d) => d.memberId === memberId)
}

export function getForcedSuccessByWeek(tenantId: TenantId, weekOf: string): ForcedSuccessItem[] {
  const memberIds = getMembersByTenant(tenantId).map((m) => m.id)
  return mockForcedSuccessItems.filter((fs) => memberIds.includes(fs.memberId) && fs.weekOf === weekOf)
}

export const mockWrapped: MemberWrapped[] = mockMembers.slice(0, 10).map((member) => ({
  memberId: member.id,
  period: "2025",
  startSnapshot: {
    goals: ["Scale revenue", "Build team", "Enter new market"],
    bottlenecks: ["Limited pipeline", "Hiring challenges", "Brand awareness"],
    riskTier: "yellow" as const,
  },
  currentSnapshot: {
    goals: member.truthProfile?.goals ?? ["Continue growth", "Optimize operations"],
    bottlenecks: member.truthProfile?.bottlenecks ?? ["Market conditions"],
    riskTier: member.riskTier,
  },
  highlights: {
    introsReceived: Math.floor(Math.random() * 12) + 3,
    perksUsed: Math.floor(Math.random() * 8) + 1,
    eventsAttended: Math.floor(Math.random() * 15) + 5,
    resourcesAccessed: Math.floor(Math.random() * 20) + 10,
    sentimentTrend: member.riskTier === "green" ? "improving" : member.riskTier === "red" ? "declining" : "stable",
  },
  wins: [
    "Closed $500K deal through club intro",
    "Hired VP of Marketing from member referral",
    "Launched product feature based on mastermind feedback",
    "Expanded into EMEA market",
  ].slice(0, Math.floor(Math.random() * 3) + 2),
  generatedAt: new Date().toISOString(),
}))
